### ISSUE TITLE
ImportError: No module named parse

### ISSUE THREAD

**Issue by Tyree** [pkoenig10/sink#29]
Getting an error when I try to run sink now. I've been running sink for months with no issue. :-/
```
Traceback (most recent call last):
  File "sink.py", line 8, in <module>
    import urllib.parse, urllib.request
ImportError: No module named parse
```
Any ideas?

**Comment by Tyree** [comment]
Update. If I specify to use python version 3, I get another error:
```
py -3 sink.py update
Traceback (most recent call last):
  File "sink.py", line 18, in <module>
    import mechanicalsoup
ModuleNotFoundError: No module named 'mechanicalsoup'
PS C:\Users\Matt Tyree\sink>
```

**Comment by Tyree** [comment]
Uninstalled Python and started over. Works now. Sorry!
