### ISSUE TITLE
Error when trying to sync contacts

### ISSUE THREAD

**Issue by mbmccormick** [pkoenig10/sink#3]
This has worked for me before (albeit, I am using a brand new sinkshelf), but now it does not seem to be working after a fresh install:

```
PS C:\Users\Matt\Documents\GitHub\sink> python sink.py update
Authorizing Google...
Getting Google contacts...
88 contacts
Authorizing Facebook...
Facebook username: <redacted>
Facebook password:
Getting Facebook friends...
147 friends
Updating links...
Traceback (most recent call last):
  File "sink.py", line 432, in <module>
    main()
  File "sink.py", line 395, in main
    sink.update(args.update_ignored, args.auto_only, args.score_threshold, args.match_limit, args.retries)
  File "sink.py", line 250, in update
    self._update_links(update_ignored, auto_only, score_threshold, match_limit)
  File "sink.py", line 300, in _update_links
    matches = self._get_matches(self.contacts[contact_url], match_limit)
  File "sink.py", line 371, in _get_matches
    return process.extract(name, self.friends.keys(), processor=lambda friend_url: self.friends[friend_url], scorer=fuzz
.UWRatio, limit=match_limit)
  File "C:\Python27\lib\site-packages\fuzzywuzzy\process.py", line 178, in extract
    return heapq.nlargest(limit, sl, key=lambda i: i[1]) if limit is not None else \
  File "C:\Python27\lib\heapq.py", line 470, in nlargest
    result = _nlargest(n, it)
  File "C:\Python27\lib\site-packages\fuzzywuzzy\process.py", line 102, in extractWithoutOrder
    processed_query = processor(query)
  File "sink.py", line 371, in <lambda>
    return process.extract(name, self.friends.keys(), processor=lambda friend_url: self.friends[friend_url], scorer=fuzz
.UWRatio, limit=match_limit)
KeyError: '<redacted>'
```

**Comment by pkoenig10** [comment]
This was caused by an updated version of [fuzzywuzzy](https://github.com/seatgeek/fuzzywuzzy).  Fuzzywuzzy now supports fuzzy matching dictionary values so my lambda function is no longer needed.

**Comment by mbmccormick** [comment]
Thanks for the quick turnaround! However, now I am hitting a different error:

```
PS C:\Users\Matt\Documents\GitHub\sink> python sink.py update
Authorizing Google...
Getting Google contacts...
88 contacts
Authorizing Facebook...
Facebook username: <redacted>
Facebook password:
Getting Facebook friends...
147 friends
Updating links...
Traceback (most recent call last):
  File "sink.py", line 432, in <module>
    main()
  File "sink.py", line 395, in main
    sink.update(args.update_ignored, args.auto_only, args.score_threshold, args.match_limit, args.retries)
  File "sink.py", line 250, in update
    self._update_links(update_ignored, auto_only, score_threshold, match_limit)
  File "sink.py", line 302, in _update_links
    self._add_link(contact_url, matches[0][0])
  File "sink.py", line 339, in _add_link
    self._print_link(contact_url)
  File "sink.py", line 368, in _print_link
    print "%s%s <- %s" % (prefix, self.contacts[contact_url], self.friends[friend_url])
KeyError: u'John Smith'
```
